[2024-03-08 16:52:38,765] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-07T13:00:00+00:00 [queued]>
[2024-03-08 16:52:38,796] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-07T13:00:00+00:00 [queued]>
[2024-03-08 16:52:38,796] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-08 16:52:38,797] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-03-08 16:52:38,797] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-08 16:52:38,848] {taskinstance.py:1107} INFO - Executing <Task(EmrAddStepsOperator): add_step_to_emr_cluster> on 2024-03-07T13:00:00+00:00
[2024-03-08 16:52:38,853] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2024-03-08 16:52:38,860] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 's3_to_hdfs_on_emr', 'add_step_to_emr_cluster', '2024-03-07T13:00:00+00:00', '--job-id', '212', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmptk_xnbuw', '--error-file', '/tmp/tmp93npurc_']
[2024-03-08 16:52:38,862] {standard_task_runner.py:77} INFO - Job 212: Subtask add_step_to_emr_cluster
[2024-03-08 16:52:38,945] {logging_mixin.py:104} INFO - Running <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-07T13:00:00+00:00 [running]> on host 21364be1879d
[2024-03-08 16:52:39,038] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1294, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1795, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1003, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1016, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1067, in render_template
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1067, in <listcomp>
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1070, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1070, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1070, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1070, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in content.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1067, in render_template
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1067, in <listcomp>
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1051, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: s3://myprojectemr/myinputfolder/tweets.json
[2024-03-08 16:52:39,041] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=s3_to_hdfs_on_emr, task_id=add_step_to_emr_cluster, execution_date=20240307T130000, start_date=20240308T165238, end_date=20240308T165239
[2024-03-08 16:52:39,117] {local_task_job.py:151} INFO - Task exited with return code 1
