[2024-03-04 09:48:53,557] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-04T04:00:00+00:00 [queued]>
[2024-03-04 09:48:53,602] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-04T04:00:00+00:00 [queued]>
[2024-03-04 09:48:53,602] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-04 09:48:53,603] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-04 09:48:53,604] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-04 09:48:53,669] {taskinstance.py:1107} INFO - Executing <Task(EmrAddStepsOperator): add_step_to_emr_cluster> on 2024-03-04T04:00:00+00:00
[2024-03-04 09:48:53,673] {standard_task_runner.py:52} INFO - Started process 36 to run task
[2024-03-04 09:48:53,681] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 's3_to_hdfs_on_emr', 'add_step_to_emr_cluster', '2024-03-04T04:00:00+00:00', '--job-id', '59', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmpnsv82za_', '--error-file', '/tmp/tmp0izi1guj']
[2024-03-04 09:48:53,683] {standard_task_runner.py:77} INFO - Job 59: Subtask add_step_to_emr_cluster
[2024-03-04 09:48:53,801] {logging_mixin.py:104} INFO - Running <TaskInstance: s3_to_hdfs_on_emr.add_step_to_emr_cluster 2024-03-04T04:00:00+00:00 [running]> on host 9791eaa2625d
[2024-03-04 09:48:53,978] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=s3_to_hdfs_on_emr
AIRFLOW_CTX_TASK_ID=add_step_to_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2024-03-04T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-04T04:00:00+00:00
[2024-03-04 09:48:53,979] {base_aws.py:368} INFO - Airflow Connection: aws_conn_id=aws_default
[2024-03-04 09:48:53,996] {base_aws.py:166} INFO - Credentials retrieved from login
[2024-03-04 09:48:53,997] {base_aws.py:82} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2024-03-04 09:48:53,997] {base_aws.py:84} INFO - Creating session with aws_access_key_id=AKIA4MTWLLCCM67BOY3J region_name=us-east-1
[2024-03-04 09:48:54,017] {base_aws.py:157} INFO - role_arn is None
[2024-03-04 09:48:54,287] {emr_add_steps.py:90} INFO - Adding steps to j-E65C9OZZ8BJF
[2024-03-04 09:48:55,876] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/emr_add_steps.py", line 98, in execute
    response = emr.add_job_flow_steps(JobFlowId=job_flow_id, Steps=steps)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the AddJobFlowSteps operation: User: arn:aws:iam::851725473924:user/hadoopuser is not authorized to perform: elasticmapreduce:AddJobFlowSteps on resource: arn:aws:elasticmapreduce:us-east-1:851725473924:cluster/j-E65C9OZZ8BJF because no identity-based policy allows the elasticmapreduce:AddJobFlowSteps action
[2024-03-04 09:48:55,886] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_to_hdfs_on_emr, task_id=add_step_to_emr_cluster, execution_date=20240304T040000, start_date=20240304T094853, end_date=20240304T094855
[2024-03-04 09:48:56,111] {local_task_job.py:151} INFO - Task exited with return code 1
